import { generateFiles } from "fumadocs-openapi";
import { writeFile } from "fs/promises";
import { routes } from "@countify/api/src/index";
import { rimraf } from "rimraf";
import { stringify } from "yaml";

async function main() {
  await rimraf("./content/docs/api", {
    filter(v) {
      return !v.endsWith("index.mdx") && !v.endsWith("meta.json");
    },
  });

  await writeFile(
    "api.yaml",
    `
# This file is automatically generated by the script in \`scripts/build-api.ts\`.
# Do not edit manually.
${stringify(
  routes.getOpenAPIDocument({
    openapi: "3.0.0",
    info: {
      title: "Countify API",
      version: "3.0.0-alpha.1",
    },
    servers: [
      {
        url: "https://api.countify.fun",
      },
    ],
  })
)}
`.trim()
  );

  await generateFiles({
    input: "api.yaml",
    output: "./content/docs/api",
    per: "operation",
  });

  process.exit(0);
}

main();
